[spoe-inspector]
    spoe-agent spoe-inspector
    timeout hello      5s
    timeout idle       2m
    timeout processing 30s
    messages inspect
    option var-prefix agent
    use-backend spop_agent

spoe-message inspect
    args arg_ver=req.ver arg_method=method arg_hostname=req.hdr(Host) arg_ssl=ssl_fc arg_hdrs=req.hdr arg_pathq=pathq arg_body=req.body arg_backends=str(apache|default)
    event on-frontend-http-request
